<?php
$countryCodes = [
    ['code' => '93', 'name' => 'Afghanistan', 'iso' => 'AF'],
    ['code' => '355', 'name' => 'Albania', 'iso' => 'AL'],
    ['code' => '213', 'name' => 'Algeria', 'iso' => 'DZ'],
    ['code' => '1-684', 'name' => 'American Samoa', 'iso' => 'AS'],
    ['code' => '376', 'name' => 'Andorra', 'iso' => 'AD'],
    ['code' => '244', 'name' => 'Angola', 'iso' => 'AO'],
    ['code' => '1-268', 'name' => 'Antigua and Barbuda', 'iso' => 'AG'],
    ['code' => '54', 'name' => 'Argentina', 'iso' => 'AR'],
    ['code' => '374', 'name' => 'Armenia', 'iso' => 'AM'],
    ['code' => '61', 'name' => 'Australia', 'iso' => 'AU'],
    ['code' => '43', 'name' => 'Austria', 'iso' => 'AT'],
    ['code' => '994', 'name' => 'Azerbaijan', 'iso' => 'AZ'],

    ['code' => '973', 'name' => 'Bahrain', 'iso' => 'BH'],
    ['code' => '880', 'name' => 'Bangladesh', 'iso' => 'BD'],
    ['code' => '1-246', 'name' => 'Barbados', 'iso' => 'BB'],
    ['code' => '375', 'name' => 'Belarus', 'iso' => 'BY'],
    ['code' => '32', 'name' => 'Belgium', 'iso' => 'BE'],
    ['code' => '501', 'name' => 'Belize', 'iso' => 'BZ'],
    ['code' => '229', 'name' => 'Benin', 'iso' => 'BJ'],
    ['code' => '975', 'name' => 'Bhutan', 'iso' => 'BT'],
    ['code' => '591', 'name' => 'Bolivia', 'iso' => 'BO'],
    ['code' => '387', 'name' => 'Bosnia and Herzegovina', 'iso' => 'BA'],
    ['code' => '267', 'name' => 'Botswana', 'iso' => 'BW'],
    ['code' => '55', 'name' => 'Brazil', 'iso' => 'BR'],
    ['code' => '673', 'name' => 'Brunei', 'iso' => 'BN'],
    ['code' => '359', 'name' => 'Bulgaria', 'iso' => 'BG'],

    ['code' => '855', 'name' => 'Cambodia', 'iso' => 'KH'],
    ['code' => '237', 'name' => 'Cameroon', 'iso' => 'CM'],
    ['code' => '1', 'name' => 'Canada', 'iso' => 'CA'],
    ['code' => '238', 'name' => 'Cape Verde', 'iso' => 'CV'],
    ['code' => '236', 'name' => 'Central African Republic', 'iso' => 'CF'],
    ['code' => '235', 'name' => 'Chad', 'iso' => 'TD'],
    ['code' => '56', 'name' => 'Chile', 'iso' => 'CL'],
    ['code' => '86', 'name' => 'China', 'iso' => 'CN'],
    ['code' => '57', 'name' => 'Colombia', 'iso' => 'CO'],
    ['code' => '269', 'name' => 'Comoros', 'iso' => 'KM'],
    ['code' => '242', 'name' => 'Congo', 'iso' => 'CG'],
    ['code' => '506', 'name' => 'Costa Rica', 'iso' => 'CR'],
    ['code' => '385', 'name' => 'Croatia', 'iso' => 'HR'],
    ['code' => '53', 'name' => 'Cuba', 'iso' => 'CU'],
    ['code' => '357', 'name' => 'Cyprus', 'iso' => 'CY'],
    ['code' => '420', 'name' => 'Czech Republic', 'iso' => 'CZ'],

    ['code' => '45', 'name' => 'Denmark', 'iso' => 'DK'],
    ['code' => '253', 'name' => 'Djibouti', 'iso' => 'DJ'],
    ['code' => '1-767', 'name' => 'Dominica', 'iso' => 'DM'],
    ['code' => '1-809', 'name' => 'Dominican Republic', 'iso' => 'DO'],

    ['code' => '20', 'name' => 'Egypt', 'iso' => 'EG'],
    ['code' => '503', 'name' => 'El Salvador', 'iso' => 'SV'],
    ['code' => '291', 'name' => 'Eritrea', 'iso' => 'ER'],
    ['code' => '372', 'name' => 'Estonia', 'iso' => 'EE'],
    ['code' => '251', 'name' => 'Ethiopia', 'iso' => 'ET'],

    ['code' => '33', 'name' => 'France', 'iso' => 'FR'],
    ['code' => '49', 'name' => 'Germany', 'iso' => 'DE'],
    ['code' => '30', 'name' => 'Greece', 'iso' => 'GR'],
    ['code' => '852', 'name' => 'Hong Kong', 'iso' => 'HK'],
    ['code' => '36', 'name' => 'Hungary', 'iso' => 'HU'],

    ['code' => '91', 'name' => 'India', 'iso' => 'IN'],
    ['code' => '62', 'name' => 'Indonesia', 'iso' => 'ID'],
    ['code' => '98', 'name' => 'Iran', 'iso' => 'IR'],
    ['code' => '964', 'name' => 'Iraq', 'iso' => 'IQ'],
    ['code' => '353', 'name' => 'Ireland', 'iso' => 'IE'],
    ['code' => '972', 'name' => 'Israel', 'iso' => 'IL'],
    ['code' => '39', 'name' => 'Italy', 'iso' => 'IT'],

    ['code' => '81', 'name' => 'Japan', 'iso' => 'JP'],
    ['code' => '962', 'name' => 'Jordan', 'iso' => 'JO'],

    ['code' => '254', 'name' => 'Kenya', 'iso' => 'KE'],
    ['code' => '965', 'name' => 'Kuwait', 'iso' => 'KW'],

    ['code' => '60', 'name' => 'Malaysia', 'iso' => 'MY'],
    ['code' => '52', 'name' => 'Mexico', 'iso' => 'MX'],
    ['code' => '212', 'name' => 'Morocco', 'iso' => 'MA'],

    ['code' => '31', 'name' => 'Netherlands', 'iso' => 'NL'],
    ['code' => '64', 'name' => 'New Zealand', 'iso' => 'NZ'],
    ['code' => '234', 'name' => 'Nigeria', 'iso' => 'NG'],
    ['code' => '47', 'name' => 'Norway', 'iso' => 'NO'],

    ['code' => '92', 'name' => 'Pakistan', 'iso' => 'PK'],
    ['code' => '63', 'name' => 'Philippines', 'iso' => 'PH'],
    ['code' => '48', 'name' => 'Poland', 'iso' => 'PL'],
    ['code' => '351', 'name' => 'Portugal', 'iso' => 'PT'],

    ['code' => '974', 'name' => 'Qatar', 'iso' => 'QA'],

    ['code' => '7', 'name' => 'Russia', 'iso' => 'RU'],
    ['code' => '40', 'name' => 'Romania', 'iso' => 'RO'],

    ['code' => '966', 'name' => 'Saudi Arabia', 'iso' => 'SA'],
    ['code' => '65', 'name' => 'Singapore', 'iso' => 'SG'],
    ['code' => '27', 'name' => 'South Africa', 'iso' => 'ZA'],
    ['code' => '82', 'name' => 'South Korea', 'iso' => 'KR'],
    ['code' => '34', 'name' => 'Spain', 'iso' => 'ES'],
    ['code' => '94', 'name' => 'Sri Lanka', 'iso' => 'LK'],
    ['code' => '46', 'name' => 'Sweden', 'iso' => 'SE'],
    ['code' => '41', 'name' => 'Switzerland', 'iso' => 'CH'],

    ['code' => '66', 'name' => 'Thailand', 'iso' => 'TH'],
    ['code' => '90', 'name' => 'Turkey', 'iso' => 'TR'],

    ['code' => '971', 'name' => 'United Arab Emirates', 'iso' => 'AE'],
    ['code' => '44', 'name' => 'United Kingdom', 'iso' => 'GB'],
    ['code' => '1', 'name' => 'United States', 'iso' => 'US'],

    ['code' => '84', 'name' => 'Vietnam', 'iso' => 'VN'],
    ['code' => '263', 'name' => 'Zimbabwe', 'iso' => 'ZW'],
];
